version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:8080'
>>>>>>> 7a1a0c164f0e6bcc0c93f7908d9475ab97ff94f0
    volumes:
      - .:/var/www/html/finance
    ports:
      - '3000:8080'
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
