version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - '9000:9000'
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
